name: Build React Service
description: Common build steps for React microfrontend
inputs:
  service:
    description: Working directory for the service
    required: true
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20.x"

    - name: Install NPM Dependencies
      working-directory: Frontends/${{ inputs.service }}
      shell: bash
      run: npm install --retry 5 --fetch-retries 5 --fetch-retry-mintimeout 20000

    - name: Lint Source Code
      working-directory: Frontends/${{ inputs.service }}
      shell: bash
      run: npm run lint

    - name: Check Code Formatting
      working-directory: Frontends/${{ inputs.service }}
      shell: bash
      run: npm run format:check

    - name: Build React App
      working-directory: Frontends/${{ inputs.service }}
      shell: bash
      run: npm run build

    - name: Run React Tests
      working-directory: Frontends/${{ inputs.service }}
      shell: bash
      run: npm run test
