image: gitpod/workspace-dotnet

vscode:
  extensions:
    - ms-dotnettools.vscode-dotnet-runtime
    - ms-dotnettools.csharp
    - dbaeumer.vscode-eslint
    - dsznajder.es7-react-js-snippets

tasks:
  - name: Restore .NET packages for ${SERVICE}
    _matrix:
      SERVICE:
        - CompanyAPI
        - IdentityAPI
        - DJHostGateway
        - DocumentsAPI
        - EquipmentAPI
        - MailingAPI
        - MusicAPI
        - PartyAPI
    init: |
      cd Services/${SERVICE}
      dotnet restore

  - name: Install Dependencies for ${FRONTEND}
    _matrix:
      FRONTEND:
        - DJPanel
        - Identity
        - Music
    init: |
      cd Frontends/${FRONTEND}
      npm install