name: Checkout Repository
description: Standard checkout of the repository
inputs:
  ref:
    description: The branch, tag or SHA to checkout
    required: false
  fetch-depth:
    description: Number of commits to fetch. 0 indicates all history
    required: false
    default: '1'
runs:
  using: composite
  steps:
    - name: Checkout source code
      uses: actions/checkout@v5
      with:
        ref: ${{ inputs.ref }}
        fetch-depth: ${{ inputs.fetch-depth }}
