{{- range .Values.strapi }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: {{ .image }}
          ports:
            - containerPort: 1337
          volumeMounts:
            - name: strapi-app
              mountPath: {{ .mountPath | default "/srv/app" }}
      volumes:
        - name: strapi-app
          hostPath:
            path: {{ .hostPath | default "/mnt/{{ .name }}-app" }}
            type: DirectoryOrCreate
---
{{- end }}