apiVersion: v2
kubeVersion: ">=1.21.0"
name: djpanel
version: 0.1.0
appVersion: "1.0.0"
description: A Helm chart for deploying the DJPanel microservices stack (Strapi, SQL Server, MongoDB, Redis, RabbitMQ, .NET microservices, React frontend)
type: application
deprecated: false
home: https://github.com/psptorchinim/micros
icon: https://truecharts.org/_astro/with-text.BkfXtZ60.svg
keywords:
  - djpanel
  - microservices
  - dotnet
  - strapi
  - react
  - kubernetes
sources:
  - https://github.com/psptorchinim/micros
dependencies:
  - name: mongodb
    repository: "https://charts.bitnami.com/bitnami"
    version: "13.6.0"
    condition: mongodb.enabled
    tags:
      - database
    alias: djpanel-mongodb
  - name: redis
    repository: "https://charts.bitnami.com/bitnami"
    version: "17.3.2"
    condition: redis.enabled
    tags:
      - cache
    alias: djpanel-redis
maintainers:
  - name: DJBeatBlaster
    email: contact@djbeatblaster.com
    url: https://github.com/psptorchinim/micros
annotations:
  example: "This chart is used for deploying the DJPanel microservices stack."
