version: "3.9"

services:
  mongodb_container:
    image: mongo:latest
    restart: unless-stopped
    pull_policy: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USER_MONGODB}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD_MONGODB}
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD-SHELL", 'mongosh --eval "db.adminCommand(\'ping\')" || mongo --eval "db.adminCommand(\'ping\')"']
      interval: 10s
      timeout: 15s
      retries: 10
    networks:
      - mongo_net
      - public
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb

  strapi_db:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${CMS_DATABASE_NAME}
      - POSTGRES_USER=${CMS_DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${CMS_DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${CMS_DATABASE_USERNAME}"]
      interval: 10s
      timeout: 15s
      retries: 10
    networks:
      - strapi
      - public
    volumes:
      - pg_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:latest
    restart: unless-stopped
    pull_policy: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 15s
      retries: 10
    networks:
      - rabbitmq_net
      - public
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: bitnami/redis:latest
    restart: unless-stopped
    pull_policy: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", 'redis-cli -a "${REDIS_PASSWORD}" ping | grep PONG']
      interval: 10s
      timeout: 15s
      retries: 10
    networks:
      - redis_net
      - public
    volumes:
      - redis_data:/data

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    pull_policy: always
    environment:
      - MSSQL_SA_PASSWORD=${DATABASE_PASSWORD_SQLSERVER}
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -U ${DATABASE_USER_SQLSERVER} -P ${DATABASE_PASSWORD_SQLSERVER} -Q 'SELECT 1' -C || exit 1"]
      interval: 10s
      timeout: 15s
      retries: 10
    networks:
      - sql_net
      - public
    volumes:
      - mssql_data:/var/opt/mssql

  strapi:
    image: strapi/strapi:latest
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: ${CMS_DATABASE_CLIENT}
      DATABASE_HOST: strapi_db
      DATABASE_PORT: ${CMS_DATABASE_PORT}
      DATABASE_NAME: ${CMS_DATABASE_NAME}
      DATABASE_USERNAME: ${CMS_DATABASE_USERNAME}
      DATABASE_PASSWORD: ${CMS_DATABASE_PASSWORD}
      JWT_SECRET: ${CMS_JWT_SECRET}
      ADMIN_JWT_SECRET: ${CMS_ADMIN_JWT_SECRET}
      APP_KEYS: ${CMS_APP_KEYS}
      NODE_ENV: ${CMS_NODE_ENV}
    ports:
      - "1337:1337"
    networks:
      - strapi
      - public
      - strapi_fe_net
    depends_on:
      strapi_db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:1337/admin || exit 1"]
      interval: 10s
      timeout: 15s
      retries: 10
    volumes:
      - strapi_app:/srv/app

  apigateway:
    build:
      context: .
      dockerfile: Docker/microservice.Dockerfile
      args:
        MICROSERVICE_NAME: djhostgateway
        DATABASE_HOST_SQLSERVER: ${DATABASE_HOST_SQLSERVER}
        DATABASE_PORT_SQLSERVER: ${DATABASE_PORT_SQLSERVER}
        DATABASE_USER_SQLSERVER: ${DATABASE_USER_SQLSERVER}
        DATABASE_PASSWORD_SQLSERVER: ${DATABASE_PASSWORD_SQLSERVER}
        DATABASE_HOST_MONGODB: ${DATABASE_HOST_MONGODB}
        DATABASE_PORT_MONGODB: ${DATABASE_PORT_MONGODB}
        DATABASE_USER_MONGODB: ${DATABASE_USER_MONGODB}
        DATABASE_PASSWORD_MONGODB: ${DATABASE_PASSWORD_MONGODB}
        REDIS_HOST: ${REDIS_HOST}
        REDIS_PORT: ${REDIS_PORT}
        REDIS_PASSWORD: ${REDIS_PASSWORD}
        RABBITMQ_HOST: ${RABBITMQ_HOST}
        RABBITMQ_PORT: ${RABBITMQ_PORT}
        RABBITMQ_USER: ${RABBITMQ_USER}
        RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
        SECURE_KEY: ${SECURE_KEY}
        JWT_KEY: ${JWT_KEY}
        ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
        ASPNETCORE_IDENTITY_BE_ADDRESS: ${ASPNETCORE_IDENTITY_BE_ADDRESS}
        ASPNETCORE_MUSIC_BE_ADDRESS: ${ASPNETCORE_MUSIC_BE_ADDRESS}
        ASPNETCORE_GEAR_BE_ADDRESS: ${ASPNETCORE_GEAR_BE_ADDRESS}
        ASPNETCORE_DOCUMENTS_BE_ADDRESS: ${ASPNETCORE_DOCUMENTS_BE_ADDRESS}
        ASPNETCORE_BRAND_BE_ADDRESS: ${ASPNETCORE_BRAND_BE_ADDRESS}
        ASPNETCORE_PARTY_BE_ADDRESS: ${ASPNETCORE_PARTY_BE_ADDRESS}
        ASPNETCORE_MAILING_BE_ADDRESS: ${ASPNETCORE_MAILING_BE_ADDRESS}
        DATABASE_CATALOG: ${DATABASE_CATALOG}
        DJPANEL_USER_EMAIL: ${DJPANEL_USER_EMAIL}
        DJPANEL_USER_PASSWORD: ${DJPANEL_USER_PASSWORD}
    restart: unless-stopped
    pull_policy: always
    ports:
      - "3000:8080"
    depends_on:
      brand_be:
        condition: service_healthy
      documents_be:
        condition: service_healthy
      gear_be:
        condition: service_healthy
      identity_be:
        condition: service_healthy
      mailing_be:
        condition: service_healthy
      music_be:
        condition: service_healthy
      party_be:
        condition: service_healthy
    networks:
      - apigw_backends_net
      - apigw_fe_net
      - public

  host_fe:
    build:
      context: .
      dockerfile: Docker/microfrontend.Dockerfile
      args:
        MICROFRONTEND_NAME: dj-panel
        REACT_APP_API_GATEWAY: ${REACT_APP_API_GATEWAY}
        REACT_APP_API_SECURE_KEY: ${REACT_APP_API_SECURE_KEY}
        REACT_APP_API_JWT_TOKEN: ${REACT_APP_API_JWT_TOKEN}
    restart: unless-stopped
    pull_policy: always
    ports:
      - "3080:3000"
    networks:
      - rabbitmq_net
      - apigw_fe_net
      - public
      - strapi_fe_net
    depends_on:
      apigateway:
        condition: service_healthy
      strapi:
        condition: service_healthy

  identity_be:
    build:
      context: .
      dockerfile: Docker/microservice.Dockerfile
      args:
        MICROSERVICE_NAME: identityapi
        DATABASE_HOST_SQLSERVER: ${DATABASE_HOST_SQLSERVER}
        DATABASE_PORT_SQLSERVER: ${DATABASE_PORT_SQLSERVER}
        DATABASE_USER_SQLSERVER: ${DATABASE_USER_SQLSERVER}
        DATABASE_PASSWORD_SQLSERVER: ${DATABASE_PASSWORD_SQLSERVER}
        DATABASE_HOST_MONGODB: ${DATABASE_HOST_MONGODB}
        DATABASE_PORT_MONGODB: ${DATABASE_PORT_MONGODB}
        DATABASE_USER_MONGODB: ${DATABASE_USER_MONGODB}
        DATABASE_PASSWORD_MONGODB: ${DATABASE_PASSWORD_MONGODB}
        REDIS_HOST: ${REDIS_HOST}
        REDIS_PORT: ${REDIS_PORT}
        REDIS_PASSWORD: ${REDIS_PASSWORD}
        RABBITMQ_HOST: ${RABBITMQ_HOST}
        RABBITMQ_PORT: ${RABBITMQ_PORT}
        RABBITMQ_USER: ${RABBITMQ_USER}
        RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
        SECURE_KEY: ${SECURE_KEY}
        JWT_KEY: ${JWT_KEY}
        ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
        ASPNETCORE_IDENTITY_BE_ADDRESS: ${ASPNETCORE_IDENTITY_BE_ADDRESS}
        ASPNETCORE_MUSIC_BE_ADDRESS: ${ASPNETCORE_MUSIC_BE_ADDRESS}
        ASPNETCORE_GEAR_BE_ADDRESS: ${ASPNETCORE_GEAR_BE_ADDRESS}
        ASPNETCORE_DOCUMENTS_BE_ADDRESS: ${ASPNETCORE_DOCUMENTS_BE_ADDRESS}
        ASPNETCORE_BRAND_BE_ADDRESS: ${ASPNETCORE_BRAND_BE_ADDRESS}
        ASPNETCORE_PARTY_BE_ADDRESS: ${ASPNETCORE_PARTY_BE_ADDRESS}
        ASPNETCORE_MAILING_BE_ADDRESS: ${ASPNETCORE_MAILING_BE_ADDRESS}
        DATABASE_CATALOG: ${DATABASE_CATALOG}
        DJPANEL_USER_EMAIL: ${DJPANEL_USER_EMAIL}
        DJPANEL_USER_PASSWORD: ${DJPANEL_USER_PASSWORD}
    restart: unless-stopped
    pull_policy: always
    expose:
      - "8080"
    depends_on:
      sqlserver:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - sql_net
      - redis_net
      - apigw_backends_net
      - rabbitmq_net

  music_be:
    build:
      context: .
      dockerfile: Docker/microservice.Dockerfile
      args:
        MICROSERVICE_NAME: musicapi
        DATABASE_HOST_SQLSERVER: ${DATABASE_HOST_SQLSERVER}
        DATABASE_PORT_SQLSERVER: ${DATABASE_PORT_SQLSERVER}
        DATABASE_USER_SQLSERVER: ${DATABASE_USER_SQLSERVER}
        DATABASE_PASSWORD_SQLSERVER: ${DATABASE_PASSWORD_SQLSERVER}
        DATABASE_HOST_MONGODB: ${DATABASE_HOST_MONGODB}
        DATABASE_PORT_MONGODB: ${DATABASE_PORT_MONGODB}
        DATABASE_USER_MONGODB: ${DATABASE_USER_MONGODB}
        DATABASE_PASSWORD_MONGODB: ${DATABASE_PASSWORD_MONGODB}
        REDIS_HOST: ${REDIS_HOST}
        REDIS_PORT: ${REDIS_PORT}
        REDIS_PASSWORD: ${REDIS_PASSWORD}
        RABBITMQ_HOST: ${RABBITMQ_HOST}
        RABBITMQ_PORT: ${RABBITMQ_PORT}
        RABBITMQ_USER: ${RABBITMQ_USER}
        RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
        SECURE_KEY: ${SECURE_KEY}
        JWT_KEY: ${JWT_KEY}
        ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
        ASPNETCORE_IDENTITY_BE_ADDRESS: ${ASPNETCORE_IDENTITY_BE_ADDRESS}
        ASPNETCORE_MUSIC_BE_ADDRESS: ${ASPNETCORE_MUSIC_BE_ADDRESS}
        ASPNETCORE_GEAR_BE_ADDRESS: ${ASPNETCORE_GEAR_BE_ADDRESS}
        ASPNETCORE_DOCUMENTS_BE_ADDRESS: ${ASPNETCORE_DOCUMENTS_BE_ADDRESS}
        ASPNETCORE_BRAND_BE_ADDRESS: ${ASPNETCORE_BRAND_BE_ADDRESS}
        ASPNETCORE_PARTY_BE_ADDRESS: ${ASPNETCORE_PARTY_BE_ADDRESS}
        ASPNETCORE_MAILING_BE_ADDRESS: ${ASPNETCORE_MAILING_BE_ADDRESS}
        DATABASE_CATALOG: ${DATABASE_CATALOG}
        DJPANEL_USER_EMAIL: ${DJPANEL_USER_EMAIL}
        DJPANEL_USER_PASSWORD: ${DJPANEL_USER_PASSWORD}
    restart: unless-stopped
    pull_policy: always
    expose:
      - "8080"
    depends_on:
      sqlserver:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - sql_net
      - redis_net
      - apigw_backends_net
      - rabbitmq_net

  gear_be:
    build:
      context: .
      dockerfile: Docker/microservice.Dockerfile
      args:
        MICROSERVICE_NAME: equipmentapi
        DATABASE_HOST_SQLSERVER: ${DATABASE_HOST_SQLSERVER}
        DATABASE_PORT_SQLSERVER: ${DATABASE_PORT_SQLSERVER}
        DATABASE_USER_SQLSERVER: ${DATABASE_USER_SQLSERVER}
        DATABASE_PASSWORD_SQLSERVER: ${DATABASE_PASSWORD_SQLSERVER}
        DATABASE_HOST_MONGODB: ${DATABASE_HOST_MONGODB}
        DATABASE_PORT_MONGODB: ${DATABASE_PORT_MONGODB}
        DATABASE_USER_MONGODB: ${DATABASE_USER_MONGODB}
        DATABASE_PASSWORD_MONGODB: ${DATABASE_PASSWORD_MONGODB}
        REDIS_HOST: ${REDIS_HOST}
        REDIS_PORT: ${REDIS_PORT}
        REDIS_PASSWORD: ${REDIS_PASSWORD}
        RABBITMQ_HOST: ${RABBITMQ_HOST}
        RABBITMQ_PORT: ${RABBITMQ_PORT}
        RABBITMQ_USER: ${RABBITMQ_USER}
        RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
        SECURE_KEY: ${SECURE_KEY}
        JWT_KEY: ${JWT_KEY}
        ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
        ASPNETCORE_IDENTITY_BE_ADDRESS: ${ASPNETCORE_IDENTITY_BE_ADDRESS}
        ASPNETCORE_MUSIC_BE_ADDRESS: ${ASPNETCORE_MUSIC_BE_ADDRESS}
        ASPNETCORE_GEAR_BE_ADDRESS: ${ASPNETCORE_GEAR_BE_ADDRESS}
        ASPNETCORE_DOCUMENTS_BE_ADDRESS: ${ASPNETCORE_DOCUMENTS_BE_ADDRESS}
        ASPNETCORE_BRAND_BE_ADDRESS: ${ASPNETCORE_BRAND_BE_ADDRESS}
        ASPNETCORE_PARTY_BE_ADDRESS: ${ASPNETCORE_PARTY_BE_ADDRESS}
        ASPNETCORE_MAILING_BE_ADDRESS: ${ASPNETCORE_MAILING_BE_ADDRESS}
        DATABASE_CATALOG: ${DATABASE_CATALOG}
        DJPANEL_USER_EMAIL: ${DJPANEL_USER_EMAIL}
        DJPANEL_USER_PASSWORD: ${DJPANEL_USER_PASSWORD}
    restart: unless-stopped
    pull_policy: always
    expose:
      - "8080"
    depends_on:
      sqlserver:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - sql_net
      - redis_net
      - apigw_backends_net
      - rabbitmq_net

  documents_be:
    build:
      context: .
      dockerfile: Docker/microservice.Dockerfile
      args:
        MICROSERVICE_NAME: documentsapi
        DATABASE_HOST_SQLSERVER: ${DATABASE_HOST_SQLSERVER}
        DATABASE_PORT_SQLSERVER: ${DATABASE_PORT_SQLSERVER}
        DATABASE_USER_SQLSERVER: ${DATABASE_USER_SQLSERVER}
        DATABASE_PASSWORD_SQLSERVER: ${DATABASE_PASSWORD_SQLSERVER}
        DATABASE_HOST_MONGODB: ${DATABASE_HOST_MONGODB}
        DATABASE_PORT_MONGODB: ${DATABASE_PORT_MONGODB}
        DATABASE_USER_MONGODB: ${DATABASE_USER_MONGODB}
        DATABASE_PASSWORD_MONGODB: ${DATABASE_PASSWORD_MONGODB}
        REDIS_HOST: ${REDIS_HOST}
        REDIS_PORT: ${REDIS_PORT}
        REDIS_PASSWORD: ${REDIS_PASSWORD}
        RABBITMQ_HOST: ${RABBITMQ_HOST}
        RABBITMQ_PORT: ${RABBITMQ_PORT}
        RABBITMQ_USER: ${RABBITMQ_USER}
        RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
        SECURE_KEY: ${SECURE_KEY}
        JWT_KEY: ${JWT_KEY}
        ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
        ASPNETCORE_IDENTITY_BE_ADDRESS: ${ASPNETCORE_IDENTITY_BE_ADDRESS}
        ASPNETCORE_MUSIC_BE_ADDRESS: ${ASPNETCORE_MUSIC_BE_ADDRESS}
        ASPNETCORE_GEAR_BE_ADDRESS: ${ASPNETCORE_GEAR_BE_ADDRESS}
        ASPNETCORE_DOCUMENTS_BE_ADDRESS: ${ASPNETCORE_DOCUMENTS_BE_ADDRESS}
        ASPNETCORE_BRAND_BE_ADDRESS: ${ASPNETCORE_BRAND_BE_ADDRESS}
        ASPNETCORE_PARTY_BE_ADDRESS: ${ASPNETCORE_PARTY_BE_ADDRESS}
        ASPNETCORE_MAILING_BE_ADDRESS: ${ASPNETCORE_MAILING_BE_ADDRESS}
        DATABASE_CATALOG: ${DATABASE_CATALOG}
        DJPANEL_USER_EMAIL: ${DJPANEL_USER_EMAIL}
        DJPANEL_USER_PASSWORD: ${DJPANEL_USER_PASSWORD}
    restart: unless-stopped
    pull_policy: always
    expose:
      - "8080"
    depends_on:
      mongodb_container:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - mongo_net
      - redis_net
      - rabbitmq_net
      - apigw_backends_net

  brand_be:
    build:
      context: .
      dockerfile: Docker/microservice.Dockerfile
      args:
        MICROSERVICE_NAME: companyapi
        DATABASE_HOST_SQLSERVER: ${DATABASE_HOST_SQLSERVER}
        DATABASE_PORT_SQLSERVER: ${DATABASE_PORT_SQLSERVER}
        DATABASE_USER_SQLSERVER: ${DATABASE_USER_SQLSERVER}
        DATABASE_PASSWORD_SQLSERVER: ${DATABASE_PASSWORD_SQLSERVER}
        DATABASE_HOST_MONGODB: ${DATABASE_HOST_MONGODB}
        DATABASE_PORT_MONGODB: ${DATABASE_PORT_MONGODB}
        DATABASE_USER_MONGODB: ${DATABASE_USER_MONGODB}
        DATABASE_PASSWORD_MONGODB: ${DATABASE_PASSWORD_MONGODB}
        REDIS_HOST: ${REDIS_HOST}
        REDIS_PORT: ${REDIS_PORT}
        REDIS_PASSWORD: ${REDIS_PASSWORD}
        RABBITMQ_HOST: ${RABBITMQ_HOST}
        RABBITMQ_PORT: ${RABBITMQ_PORT}
        RABBITMQ_USER: ${RABBITMQ_USER}
        RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
        SECURE_KEY: ${SECURE_KEY}
        JWT_KEY: ${JWT_KEY}
        ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
        ASPNETCORE_IDENTITY_BE_ADDRESS: ${ASPNETCORE_IDENTITY_BE_ADDRESS}
        ASPNETCORE_MUSIC_BE_ADDRESS: ${ASPNETCORE_MUSIC_BE_ADDRESS}
        ASPNETCORE_GEAR_BE_ADDRESS: ${ASPNETCORE_GEAR_BE_ADDRESS}
        ASPNETCORE_DOCUMENTS_BE_ADDRESS: ${ASPNETCORE_DOCUMENTS_BE_ADDRESS}
        ASPNETCORE_BRAND_BE_ADDRESS: ${ASPNETCORE_BRAND_BE_ADDRESS}
        ASPNETCORE_PARTY_BE_ADDRESS: ${ASPNETCORE_PARTY_BE_ADDRESS}
        ASPNETCORE_MAILING_BE_ADDRESS: ${ASPNETCORE_MAILING_BE_ADDRESS}
        DATABASE_CATALOG: ${DATABASE_CATALOG}
        DJPANEL_USER_EMAIL: ${DJPANEL_USER_EMAIL}
        DJPANEL_USER_PASSWORD: ${DJPANEL_USER_PASSWORD}
    restart: unless-stopped
    pull_policy: always
    expose:
      - "8080"
    depends_on:
      sqlserver:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - sql_net
      - redis_net
      - rabbitmq_net
      - apigw_backends_net

  mailing_be:
    build:
      context: .
      dockerfile: Docker/microservice.Dockerfile
      args:
        MICROSERVICE_NAME: mailingapi
        DATABASE_HOST_SQLSERVER: ${DATABASE_HOST_SQLSERVER}
        DATABASE_PORT_SQLSERVER: ${DATABASE_PORT_SQLSERVER}
        DATABASE_USER_SQLSERVER: ${DATABASE_USER_SQLSERVER}
        DATABASE_PASSWORD_SQLSERVER: ${DATABASE_PASSWORD_SQLSERVER}
        DATABASE_HOST_MONGODB: ${DATABASE_HOST_MONGODB}
        DATABASE_PORT_MONGODB: ${DATABASE_PORT_MONGODB}
        DATABASE_USER_MONGODB: ${DATABASE_USER_MONGODB}
        DATABASE_PASSWORD_MONGODB: ${DATABASE_PASSWORD_MONGODB}
        REDIS_HOST: ${REDIS_HOST}
        REDIS_PORT: ${REDIS_PORT}
        REDIS_PASSWORD: ${REDIS_PASSWORD}
        RABBITMQ_HOST: ${RABBITMQ_HOST}
        RABBITMQ_PORT: ${RABBITMQ_PORT}
        RABBITMQ_USER: ${RABBITMQ_USER}
        RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
        SECURE_KEY: ${SECURE_KEY}
        JWT_KEY: ${JWT_KEY}
        ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
        ASPNETCORE_IDENTITY_BE_ADDRESS: ${ASPNETCORE_IDENTITY_BE_ADDRESS}
        ASPNETCORE_MUSIC_BE_ADDRESS: ${ASPNETCORE_MUSIC_BE_ADDRESS}
        ASPNETCORE_GEAR_BE_ADDRESS: ${ASPNETCORE_GEAR_BE_ADDRESS}
        ASPNETCORE_DOCUMENTS_BE_ADDRESS: ${ASPNETCORE_DOCUMENTS_BE_ADDRESS}
        ASPNETCORE_BRAND_BE_ADDRESS: ${ASPNETCORE_BRAND_BE_ADDRESS}
        ASPNETCORE_PARTY_BE_ADDRESS: ${ASPNETCORE_PARTY_BE_ADDRESS}
        ASPNETCORE_MAILING_BE_ADDRESS: ${ASPNETCORE_MAILING_BE_ADDRESS}
        DATABASE_CATALOG: ${DATABASE_CATALOG}
        DJPANEL_USER_EMAIL: ${DJPANEL_USER_EMAIL}
        DJPANEL_USER_PASSWORD: ${DJPANEL_USER_PASSWORD}
    restart: unless-stopped
    pull_policy: always
    expose:
      - "8080"
    depends_on:
      sqlserver:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - sql_net
      - redis_net
      - rabbitmq_net
      - apigw_backends_net

  party_be:
    build:
      context: .
      dockerfile: Docker/microservice.Dockerfile
      args:
        MICROSERVICE_NAME: partyapi
        DATABASE_HOST_SQLSERVER: ${DATABASE_HOST_SQLSERVER}
        DATABASE_PORT_SQLSERVER: ${DATABASE_PORT_SQLSERVER}
        DATABASE_USER_SQLSERVER: ${DATABASE_USER_SQLSERVER}
        DATABASE_PASSWORD_SQLSERVER: ${DATABASE_PASSWORD_SQLSERVER}
        DATABASE_HOST_MONGODB: ${DATABASE_HOST_MONGODB}
        DATABASE_PORT_MONGODB: ${DATABASE_PORT_MONGODB}
        DATABASE_USER_MONGODB: ${DATABASE_USER_MONGODB}
        DATABASE_PASSWORD_MONGODB: ${DATABASE_PASSWORD_MONGODB}
        REDIS_HOST: ${REDIS_HOST}
        REDIS_PORT: ${REDIS_PORT}
        REDIS_PASSWORD: ${REDIS_PASSWORD}
        RABBITMQ_HOST: ${RABBITMQ_HOST}
        RABBITMQ_PORT: ${RABBITMQ_PORT}
        RABBITMQ_USER: ${RABBITMQ_USER}
        RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
        SECURE_KEY: ${SECURE_KEY}
        JWT_KEY: ${JWT_KEY}
        ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
        ASPNETCORE_IDENTITY_BE_ADDRESS: ${ASPNETCORE_IDENTITY_BE_ADDRESS}
        ASPNETCORE_MUSIC_BE_ADDRESS: ${ASPNETCORE_MUSIC_BE_ADDRESS}
        ASPNETCORE_GEAR_BE_ADDRESS: ${ASPNETCORE_GEAR_BE_ADDRESS}
        ASPNETCORE_DOCUMENTS_BE_ADDRESS: ${ASPNETCORE_DOCUMENTS_BE_ADDRESS}
        ASPNETCORE_BRAND_BE_ADDRESS: ${ASPNETCORE_BRAND_BE_ADDRESS}
        ASPNETCORE_PARTY_BE_ADDRESS: ${ASPNETCORE_PARTY_BE_ADDRESS}
        ASPNETCORE_MAILING_BE_ADDRESS: ${ASPNETCORE_MAILING_BE_ADDRESS}
        DATABASE_CATALOG: ${DATABASE_CATALOG}
        DJPANEL_USER_EMAIL: ${DJPANEL_USER_EMAIL}
        DJPANEL_USER_PASSWORD: ${DJPANEL_USER_PASSWORD}
    restart: unless-stopped
    pull_policy: always
    expose:
      - "8080"
    depends_on:
      sqlserver:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - sql_net
      - redis_net
      - rabbitmq_net
      - apigw_backends_net

networks:
  mongo_net:
    external: false
  redis_net:
    external: false
  rabbitmq_net:
    external: false
  sql_net:
    external: false
  apigw_backends_net:
    external: false
  apigw_fe_net:
    external: false
  strapi:
    external: false
  strapi_fe_net:
    external: false
  public:
    external: true

volumes:
  mongo_config:
    driver: local
  mongo_data:
    driver: local
  mssql_data:
    driver: local
  pg_data:
    driver: local
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local
  strapi_app:
    driver: local
