FROM grafana/grafana:latest

ARG GF_SECURITY_ADMIN_USER
ARG GF_SECURITY_ADMIN_PASSWORD

ENV GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
ENV GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}

HEALTHCHECK --interval=10s --timeout=10s --retries=5 \
  CMD curl -f http://localhost:3000/api/health || exit 1

EXPOSE 3000