FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

ARG MICROSERVICE_NAME

# Add all build-time args
ARG DATABASE_HOST_SQLSERVER
ARG DATABASE_PORT_SQLSERVER
ARG DATABASE_USER_SQLSERVER
ARG DATABASE_PASSWORD_SQLSERVER
ARG DATABASE_HOST_MONGODB
ARG DATABASE_PORT_MONGODB
ARG DATABASE_USER_MONGODB
ARG DATABASE_PASSWORD_MONGODB
ARG REDIS_HOST
ARG REDIS_PORT
ARG REDIS_PASSWORD
ARG RABBITMQ_HOST
ARG RABBITMQ_PORT
ARG RABBITMQ_USER
ARG RABBITMQ_PASSWORD
ARG SECURE_KEY
ARG JWT_KEY
ARG ASPNETCORE_ENVIRONMENT
ARG ASPNETCORE_IDENTITY_BE_ADDRESS
ARG ASPNETCORE_MUSIC_BE_ADDRESS
ARG ASPNETCORE_GEAR_BE_ADDRESS
ARG ASPNETCORE_DOCUMENTS_BE_ADDRESS
ARG ASPNETCORE_BRAND_BE_ADDRESS
ARG ASPNETCORE_PARTY_BE_ADDRESS
ARG ASPNETCORE_MAILING_BE_ADDRESS
ARG DATABASE_CATALOG
ARG DJPANEL_USER_EMAIL
ARG DJPANEL_USER_PASSWORD

# Set as ENV for runtime
ENV ASPNETCORE_DATABASE_HOST_SQLSERVER=$DATABASE_HOST_SQLSERVER
ENV ASPNETCORE_DATABASE_PORT_SQLSERVER=$DATABASE_PORT_SQLSERVER
ENV ASPNETCORE_DATABASE_USER_SQLSERVER=$DATABASE_USER_SQLSERVER
ENV ASPNETCORE_DATABASE_PASSWORD_SQLSERVER=$DATABASE_PASSWORD_SQLSERVER
ENV ASPNETCORE_DATABASE_HOST_MONGODB=$DATABASE_HOST_MONGODB
ENV ASPNETCORE_DATABASE_PORT_MONGODB=$DATABASE_PORT_MONGODB
ENV ASPNETCORE_DATABASE_USER_MONGODB=$DATABASE_USER_MONGODB
ENV ASPNETCORE_DATABASE_PASSWORD_MONGODB=$DATABASE_PASSWORD_MONGODB
ENV ASPNETCORE_REDIS_HOST=$REDIS_HOST
ENV ASPNETCORE_REDIS_PORT=$REDIS_PORT
ENV ASPNETCORE_REDIS_PASSWORD=$REDIS_PASSWORD
ENV ASPNETCORE_RABBITMQ_HOST=$RABBITMQ_HOST
ENV ASPNETCORE_RABBITMQ_PORT=$RABBITMQ_PORT
ENV ASPNETCORE_RABBITMQ_USER=$RABBITMQ_USER
ENV ASPNETCORE_RABBITMQ_PASSWORD=$RABBITMQ_PASSWORD
ENV ASPNETCORE_SECURE_KEY=$SECURE_KEY
ENV ASPNETCORE_JWT_KEY=$JWT_KEY
ENV ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENVIRONMENT
ENV ASPNETCORE_IDENTITY_BE_ADDRESS=$ASPNETCORE_IDENTITY_BE_ADDRESS
ENV ASPNETCORE_MUSIC_BE_ADDRESS=$ASPNETCORE_MUSIC_BE_ADDRESS
ENV ASPNETCORE_GEAR_BE_ADDRESS=$ASPNETCORE_GEAR_BE_ADDRESS
ENV ASPNETCORE_DOCUMENTS_BE_ADDRESS=$ASPNETCORE_DOCUMENTS_BE_ADDRESS
ENV ASPNETCORE_BRAND_BE_ADDRESS=$ASPNETCORE_BRAND_BE_ADDRESS
ENV ASPNETCORE_PARTY_BE_ADDRESS=$ASPNETCORE_PARTY_BE_ADDRESS
ENV ASPNETCORE_MAILING_BE_ADDRESS=$ASPNETCORE_MAILING_BE_ADDRESS
ENV ASPNETCORE_DATABASE_CATALOG=$DATABASE_CATALOG
ENV ASPNETCORE_DJPANEL_USER_EMAIL=$DJPANEL_USER_EMAIL
ENV ASPNETCORE_DJPANEL_USER_PASSWORD=$DJPANEL_USER_PASSWORD

RUN apt-get update

COPY ["Services/${MICROSERVICE_NAME}/", "Services/${MICROSERVICE_NAME}/"]
COPY ["Services/Shared/", "Services/Shared/"]
COPY ["Tests/${MICROSERVICE_NAME}.Tests/", "Tests/${MICROSERVICE_NAME}.Tests/"]
SHELL ["/bin/bash","-lc"]

RUN dotnet restore "Services/${MICROSERVICE_NAME}/${MICROSERVICE_NAME}.csproj"

WORKDIR Services/${MICROSERVICE_NAME}/
RUN dotnet tool install --global dotnet-ef && export PATH="$PATH:/root/.dotnet/tools"
RUN dotnet ef dbcontext list && dotnet ef migrations add InitialMigration || echo "No DbContext found, skipping migrations"

WORKDIR /
RUN dotnet restore "Services/${MICROSERVICE_NAME}/${MICROSERVICE_NAME}.csproj"
RUN dotnet test    "Services/${MICROSERVICE_NAME}/${MICROSERVICE_NAME}.csproj" -c Release --no-restore
RUN dotnet build   "Services/${MICROSERVICE_NAME}/${MICROSERVICE_NAME}.csproj" -c Release -o /app/build --no-restore
RUN dotnet publish "Services/${MICROSERVICE_NAME}/${MICROSERVICE_NAME}.csproj" -c Release -o /app/publish --no-restore /p:UseAppHost=false


FROM mcr.microsoft.com/dotnet/sdk:9.0 AS base
SHELL ["/bin/bash","-lc"]
RUN apt-get update
RUN apt-get install -y curl
EXPOSE 8080
ARG MICROSERVICE_NAME

# Add all build-time args
ARG DATABASE_HOST_SQLSERVER
ARG DATABASE_PORT_SQLSERVER
ARG DATABASE_USER_SQLSERVER
ARG DATABASE_PASSWORD_SQLSERVER
ARG DATABASE_HOST_MONGODB
ARG DATABASE_PORT_MONGODB
ARG DATABASE_USER_MONGODB
ARG DATABASE_PASSWORD_MONGODB
ARG REDIS_HOST
ARG REDIS_PORT
ARG REDIS_PASSWORD
ARG RABBITMQ_HOST
ARG RABBITMQ_PORT
ARG RABBITMQ_USER
ARG RABBITMQ_PASSWORD
ARG SECURE_KEY
ARG JWT_KEY
ARG ASPNETCORE_ENVIRONMENT
ARG ASPNETCORE_IDENTITY_BE_ADDRESS
ARG ASPNETCORE_MUSIC_BE_ADDRESS
ARG ASPNETCORE_GEAR_BE_ADDRESS
ARG ASPNETCORE_DOCUMENTS_BE_ADDRESS
ARG ASPNETCORE_BRAND_BE_ADDRESS
ARG ASPNETCORE_PARTY_BE_ADDRESS
ARG ASPNETCORE_MAILING_BE_ADDRESS
ARG DATABASE_CATALOG
ARG DJPANEL_USER_EMAIL
ARG DJPANEL_USER_PASSWORD

# Set as ENV for runtime
ENV ASPNETCORE_DATABASE_HOST_SQLSERVER=$DATABASE_HOST_SQLSERVER
ENV ASPNETCORE_DATABASE_PORT_SQLSERVER=$DATABASE_PORT_SQLSERVER
ENV ASPNETCORE_DATABASE_USER_SQLSERVER=$DATABASE_USER_SQLSERVER
ENV ASPNETCORE_DATABASE_PASSWORD_SQLSERVER=$DATABASE_PASSWORD_SQLSERVER
ENV ASPNETCORE_DATABASE_HOST_MONGODB=$DATABASE_HOST_MONGODB
ENV ASPNETCORE_DATABASE_PORT_MONGODB=$DATABASE_PORT_MONGODB
ENV ASPNETCORE_DATABASE_USER_MONGODB=$DATABASE_USER_MONGODB
ENV ASPNETCORE_DATABASE_PASSWORD_MONGODB=$DATABASE_PASSWORD_MONGODB
ENV ASPNETCORE_REDIS_HOST=$REDIS_HOST
ENV ASPNETCORE_REDIS_PORT=$REDIS_PORT
ENV ASPNETCORE_REDIS_PASSWORD=$REDIS_PASSWORD
ENV ASPNETCORE_RABBITMQ_HOST=$RABBITMQ_HOST
ENV ASPNETCORE_RABBITMQ_PORT=$RABBITMQ_PORT
ENV ASPNETCORE_RABBITMQ_USER=$RABBITMQ_USER
ENV ASPNETCORE_RABBITMQ_PASSWORD=$RABBITMQ_PASSWORD
ENV ASPNETCORE_SECURE_KEY=$SECURE_KEY
ENV ASPNETCORE_JWT_KEY=$JWT_KEY
ENV ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENVIRONMENT
ENV ASPNETCORE_IDENTITY_BE_ADDRESS=$ASPNETCORE_IDENTITY_BE_ADDRESS
ENV ASPNETCORE_MUSIC_BE_ADDRESS=$ASPNETCORE_MUSIC_BE_ADDRESS
ENV ASPNETCORE_GEAR_BE_ADDRESS=$ASPNETCORE_GEAR_BE_ADDRESS
ENV ASPNETCORE_DOCUMENTS_BE_ADDRESS=$ASPNETCORE_DOCUMENTS_BE_ADDRESS
ENV ASPNETCORE_BRAND_BE_ADDRESS=$ASPNETCORE_BRAND_BE_ADDRESS
ENV ASPNETCORE_PARTY_BE_ADDRESS=$ASPNETCORE_PARTY_BE_ADDRESS
ENV ASPNETCORE_MAILING_BE_ADDRESS=$ASPNETCORE_MAILING_BE_ADDRESS
ENV ASPNETCORE_DATABASE_CATALOG=$DATABASE_CATALOG
ENV ASPNETCORE_DJPANEL_USER_EMAIL=$DJPANEL_USER_EMAIL
ENV ASPNETCORE_DJPANEL_USER_PASSWORD=$DJPANEL_USER_PASSWORD

WORKDIR /app
COPY --from=build /app/publish/ .
ENV APP_EXE=$MICROSERVICE_NAME.dll

ENTRYPOINT dotnet /app/$APP_EXE

HEALTHCHECK --interval=10s --timeout=5s --start-period=90s --retries=6 \
  CMD curl -fsS http://localhost:8080/healthz/live \
   || curl -fsS http://localhost:8080/health \
   || curl -fsS http://localhost:8080/ \
   || exit 1
