FROM postgres:15

ARG DATABASE_NAME
ARG DATABASE_USERNAME
ARG DATABASE_PASSWORD

ENV POSTGRES_DB=$DATABASE_NAME
ENV POSTGRES_USER=$DATABASE_USERNAME
ENV POSTGRES_PASSWORD=$DATABASE_PASSWORD

HEALTHCHECK --interval=10s --timeout=15s --retries=10 CMD pg_isready -h localhost -p 5432 -d $DATABASE_NAME -U $DATABASE_USERNAME

EXPOSE 5432