FROM postgres:15

ARG DATABASE_NAME
ARG DATABASE_USERNAME
ARG DATABASE_PASSWORD

ENV POSTGRES_DB=$DATABASE_NAME
ENV POSTGRES_USER=$DATABASE_USERNAME
ENV POSTGRES_PASSWORD=$DATABASE_PASSWORD

HEALTHCHECK --interval=10s --timeout=15s --retries=10 CMD pg_isready -U "$POSTGRES_USER"

EXPOSE 5432