FROM rabbitmq:latest

ARG RABBITMQ_USER
ARG RABBITMQ_PASSWORD

ENV RABBITMQ_DEFAULT_USER=$RABBITMQ_USER
ENV RABBITMQ_DEFAULT_PASS=$RABBITMQ_PASSWORD

HEALTHCHECK --interval=10s --timeout=15s --retries=10 CMD rabbitmq-diagnostics -q ping

EXPOSE 5672 15672 15692