FROM strapi/strapi:latest

ARG CMS_DATABASE_CLIENT
ARG CMS_NODE_ENV
ARG CMS_DATABASE_NAME
ARG CMS_DATABASE_HOST
ARG CMS_DATABASE_PORT
ARG CMS_DATABASE_USERNAME
ARG CMS_DATABASE_PASSWORD
ARG CMS_JWT_SECRET
ARG CMS_ADMIN_JWT_SECRET
ARG CMS_APP_KEYS

ENV DATABASE_CLIENT=$CMS_DATABASE_CLIENT
ENV NODE_ENV=$CMS_NODE_ENV
ENV DATABASE_NAME=$CMS_DATABASE_NAME
ENV DATABASE_HOST=$CMS_DATABASE_HOST
ENV DATABASE_PORT=$CMS_DATABASE_PORT
ENV DATABASE_USERNAME=$CMS_DATABASE_USERNAME
ENV DATABASE_PASSWORD=$CMS_DATABASE_PASSWORD
ENV JWT_SECRET=$CMS_JWT_SECRET
ENV ADMIN_JWT_SECRET=$CMS_ADMIN_JWT_SECRET
ENV APP_KEYS=$CMS_APP_KEYS

HEALTHCHECK --interval=10s --timeout=15s --retries=10 CMD curl -f http://localhost:1337/admin || exit 1

EXPOSE 1337