{{- range .Values.rabbitmq }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  type: {{ if .nodePort }}NodePort{{ else }}ClusterIP{{ end }}
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
    - port: 15692
      targetPort: 15692
  selector:
    app: {{ .name }}
---
{{- end }}
