{{- range .Values.redis }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  type: {{ if .nodePort }}NodePort{{ else }}ClusterIP{{ end }}
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
  selector:
    app: {{ .name }}
---
{{- end }}
