<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <PackageJsonName Condition="$(PackageJsonName) == ''">dj-panel</PackageJsonName>
    <PackageJsonVersion Condition="$(PackageJsonVersion) == ''">1.0.0</PackageJsonVersion>
    <PackageJsonScriptsBuild Condition="$(PackageJsonScriptsBuild) == ''">cross-env NODE_OPTIONS="--max-old-space-size=4096" webpack --mode production</PackageJsonScriptsBuild>
    <PackageJsonScriptsBuildDev Condition="$(PackageJsonScriptsBuildDev) == ''">webpack --mode development</PackageJsonScriptsBuildDev>
    <PackageJsonScriptsBuildStart Condition="$(PackageJsonScriptsBuildStart) == ''">cd dist &amp;&amp; npx serve</PackageJsonScriptsBuildStart>
    <PackageJsonScriptsDev Condition="$(PackageJsonScriptsDev) == ''">webpack serve --mode development --live-reload --hot --port 3080</PackageJsonScriptsDev>
    <PackageJsonScriptsProd Condition="$(PackageJsonScriptsProd) == ''">webpack serve --mode production --port 3000</PackageJsonScriptsProd>
    <PackageJsonScriptsStaging Condition="$(PackageJsonScriptsStaging) == ''">webpack serve --mode staging --port 3000</PackageJsonScriptsStaging>
    <PackageJsonScriptsStartLive Condition="$(PackageJsonScriptsStartLive) == ''">webpack serve --mode development --live-reload --hot --port 3000</PackageJsonScriptsStartLive>
    <PackageJsonScriptsTest Condition="$(PackageJsonScriptsTest) == ''">jest --passWithNoTests</PackageJsonScriptsTest>
    <PackageJsonScriptsTestE2e Condition="$(PackageJsonScriptsTestE2e) == ''">playwright test</PackageJsonScriptsTestE2e>
    <PackageJsonScriptsTestE2eUi Condition="$(PackageJsonScriptsTestE2eUi) == ''">playwright test --ui</PackageJsonScriptsTestE2eUi>
    <PackageJsonScriptsTestE2eHeaded Condition="$(PackageJsonScriptsTestE2eHeaded) == ''">playwright test --headed</PackageJsonScriptsTestE2eHeaded>
    <PackageJsonScriptsTestAll Condition="$(PackageJsonScriptsTestAll) == ''">npm run test &amp;&amp; npm run test:e2e</PackageJsonScriptsTestAll>
    <PackageJsonScriptsLint Condition="$(PackageJsonScriptsLint) == ''">eslint "src/**/*.{js,jsx,ts,tsx}" --ignore-pattern src/models/strapi/** --ignore-pattern src/models/api/** --no-error-on-unmatched-pattern</PackageJsonScriptsLint>
    <PackageJsonScriptsLintFix Condition="$(PackageJsonScriptsLintFix) == ''">eslint "src/**/*.{js,jsx,ts,tsx}" --fix --ignore-pattern src/models/strapi/** --ignore-pattern src/models/api/** --no-error-on-unmatched-pattern</PackageJsonScriptsLintFix>
    <PackageJsonScriptsFormat Condition="$(PackageJsonScriptsFormat) == ''">prettier --check "src/**/*.{js,jsx,ts,tsx,json,css,scss,md}" --ignore-path .prettierignore</PackageJsonScriptsFormat>
    <PackageJsonScriptsFormatFix Condition="$(PackageJsonScriptsFormatFix) == ''">prettier --write "src/**/*.{js,jsx,ts,tsx,json,css,scss,md}" --ignore-path .prettierignore</PackageJsonScriptsFormatFix>
    <PackageJsonScriptsMapApi Condition="$(PackageJsonScriptsMapApi) == ''">node scripts/map-api.js</PackageJsonScriptsMapApi>
    <PackageJsonScriptsMapStrapi Condition="$(PackageJsonScriptsMapStrapi) == ''">node scripts/map-strapi.js</PackageJsonScriptsMapStrapi>
    <PackageJsonScriptsStorybook Condition="$(PackageJsonScriptsStorybook) == ''">storybook dev -p 6006</PackageJsonScriptsStorybook>
    <PackageJsonScriptsBuildStorybook Condition="$(PackageJsonScriptsBuildStorybook) == ''">cross-env NODE_OPTIONS="--localstorage-file=./node_modules/.cache/storybook-localstorage" storybook build</PackageJsonScriptsBuildStorybook>
    <PackageJsonLicense Condition="$(PackageJsonLicense) == ''">UNLICENSED</PackageJsonLicense>
    <PackageJsonAuthor Condition="$(PackageJsonAuthor) == ''">PSPTorchinim</PackageJsonAuthor>
    <PackageJsonDevdependenciesBabelCore Condition="$(PackageJsonDevdependenciesBabelCore) == ''">^7.28.4</PackageJsonDevdependenciesBabelCore>
    <PackageJsonDevdependenciesBabelPluginTransformRuntime Condition="$(PackageJsonDevdependenciesBabelPluginTransformRuntime) == ''">^7.28.3</PackageJsonDevdependenciesBabelPluginTransformRuntime>
    <PackageJsonDevdependenciesBabelPresetEnv Condition="$(PackageJsonDevdependenciesBabelPresetEnv) == ''">^7.28.3</PackageJsonDevdependenciesBabelPresetEnv>
    <PackageJsonDevdependenciesBabelPresetReact Condition="$(PackageJsonDevdependenciesBabelPresetReact) == ''">^7.27.1</PackageJsonDevdependenciesBabelPresetReact>
    <PackageJsonDevdependenciesBabelPresetTypescript Condition="$(PackageJsonDevdependenciesBabelPresetTypescript) == ''">^7.27.1</PackageJsonDevdependenciesBabelPresetTypescript>
    <PackageJsonDevdependenciesPlaywrightTest Condition="$(PackageJsonDevdependenciesPlaywrightTest) == ''">^1.56.1</PackageJsonDevdependenciesPlaywrightTest>
    <PackageJsonDevdependenciesStorybookAddonDocs Condition="$(PackageJsonDevdependenciesStorybookAddonDocs) == ''">^10.0.5</PackageJsonDevdependenciesStorybookAddonDocs>
    <PackageJsonDevdependenciesStorybookAddonOnboarding Condition="$(PackageJsonDevdependenciesStorybookAddonOnboarding) == ''">^10.0.5</PackageJsonDevdependenciesStorybookAddonOnboarding>
    <PackageJsonDevdependenciesStorybookAddonWebpack5CompilerSwc Condition="$(PackageJsonDevdependenciesStorybookAddonWebpack5CompilerSwc) == ''">^4.0.1</PackageJsonDevdependenciesStorybookAddonWebpack5CompilerSwc>
    <PackageJsonDevdependenciesStorybookReactWebpack5 Condition="$(PackageJsonDevdependenciesStorybookReactWebpack5) == ''">^10.0.5</PackageJsonDevdependenciesStorybookReactWebpack5>
    <PackageJsonDevdependenciesTestingLibraryJestDom Condition="$(PackageJsonDevdependenciesTestingLibraryJestDom) == ''">^6.8.0</PackageJsonDevdependenciesTestingLibraryJestDom>
    <PackageJsonDevdependenciesTestingLibraryReact Condition="$(PackageJsonDevdependenciesTestingLibraryReact) == ''">^16.3.0</PackageJsonDevdependenciesTestingLibraryReact>
    <PackageJsonDevdependenciesTypesBabelGenerator Condition="$(PackageJsonDevdependenciesTypesBabelGenerator) == ''">^7.27.0</PackageJsonDevdependenciesTypesBabelGenerator>
    <PackageJsonDevdependenciesTypesBabelTemplate Condition="$(PackageJsonDevdependenciesTypesBabelTemplate) == ''">^7.4.4</PackageJsonDevdependenciesTypesBabelTemplate>
    <PackageJsonDevdependenciesTypesBabelTraverse Condition="$(PackageJsonDevdependenciesTypesBabelTraverse) == ''">^7.28.0</PackageJsonDevdependenciesTypesBabelTraverse>
    <PackageJsonDevdependenciesTypesBodyParser Condition="$(PackageJsonDevdependenciesTypesBodyParser) == ''">^1.19.6</PackageJsonDevdependenciesTypesBodyParser>
    <PackageJsonDevdependenciesTypesCryptoJs Condition="$(PackageJsonDevdependenciesTypesCryptoJs) == ''">^4.2.2</PackageJsonDevdependenciesTypesCryptoJs>
    <PackageJsonDevdependenciesTypesHttpErrors Condition="$(PackageJsonDevdependenciesTypesHttpErrors) == ''">^2.0.5</PackageJsonDevdependenciesTypesHttpErrors>
    <PackageJsonDevdependenciesTypesIstanbulLibReport Condition="$(PackageJsonDevdependenciesTypesIstanbulLibReport) == ''">^3.0.3</PackageJsonDevdependenciesTypesIstanbulLibReport>
    <PackageJsonDevdependenciesTypesJest Condition="$(PackageJsonDevdependenciesTypesJest) == ''">^30.0.0</PackageJsonDevdependenciesTypesJest>
    <PackageJsonDevdependenciesTypesNode Condition="$(PackageJsonDevdependenciesTypesNode) == ''">^24.10.0</PackageJsonDevdependenciesTypesNode>
    <PackageJsonDevdependenciesTypesPropTypes Condition="$(PackageJsonDevdependenciesTypesPropTypes) == ''">^15.7.15</PackageJsonDevdependenciesTypesPropTypes>
    <PackageJsonDevdependenciesTypesQs Condition="$(PackageJsonDevdependenciesTypesQs) == ''">^6.14.0</PackageJsonDevdependenciesTypesQs>
    <PackageJsonDevdependenciesTypesRangeParser Condition="$(PackageJsonDevdependenciesTypesRangeParser) == ''">^1.2.7</PackageJsonDevdependenciesTypesRangeParser>
    <PackageJsonDevdependenciesTypesReact Condition="$(PackageJsonDevdependenciesTypesReact) == ''">^19.1.13</PackageJsonDevdependenciesTypesReact>
    <PackageJsonDevdependenciesTypesReactDom Condition="$(PackageJsonDevdependenciesTypesReactDom) == ''">^19.1.9</PackageJsonDevdependenciesTypesReactDom>
    <PackageJsonDevdependenciesTypesReactHelmet Condition="$(PackageJsonDevdependenciesTypesReactHelmet) == ''">^6.1.11</PackageJsonDevdependenciesTypesReactHelmet>
    <PackageJsonDevdependenciesTypesSend Condition="$(PackageJsonDevdependenciesTypesSend) == ''">^0.17.5</PackageJsonDevdependenciesTypesSend>
    <PackageJsonDevdependenciesTypesToughCookie Condition="$(PackageJsonDevdependenciesTypesToughCookie) == ''">^4.0.5</PackageJsonDevdependenciesTypesToughCookie>
    <PackageJsonDevdependenciesTypesYargsParser Condition="$(PackageJsonDevdependenciesTypesYargsParser) == ''">^21.0.3</PackageJsonDevdependenciesTypesYargsParser>
    <PackageJsonDevdependenciesAutoprefixer Condition="$(PackageJsonDevdependenciesAutoprefixer) == ''">^10.4.21</PackageJsonDevdependenciesAutoprefixer>
    <PackageJsonDevdependenciesBabelLoader Condition="$(PackageJsonDevdependenciesBabelLoader) == ''">^10.0.0</PackageJsonDevdependenciesBabelLoader>
    <PackageJsonDevdependenciesCssLoader Condition="$(PackageJsonDevdependenciesCssLoader) == ''">^7.1.2</PackageJsonDevdependenciesCssLoader>
    <PackageJsonDevdependenciesDotenvWebpack Condition="$(PackageJsonDevdependenciesDotenvWebpack) == ''">^8.1.1</PackageJsonDevdependenciesDotenvWebpack>
    <PackageJsonDevdependenciesEslint Condition="$(PackageJsonDevdependenciesEslint) == ''">^9.35.0</PackageJsonDevdependenciesEslint>
    <PackageJsonDevdependenciesHtmlWebpackPlugin Condition="$(PackageJsonDevdependenciesHtmlWebpackPlugin) == ''">^5.6.4</PackageJsonDevdependenciesHtmlWebpackPlugin>
    <PackageJsonDevdependenciesIdentityObjProxy Condition="$(PackageJsonDevdependenciesIdentityObjProxy) == ''">^3.0.0</PackageJsonDevdependenciesIdentityObjProxy>
    <PackageJsonDevdependenciesJest Condition="$(PackageJsonDevdependenciesJest) == ''">^30.1.3</PackageJsonDevdependenciesJest>
    <PackageJsonDevdependenciesJiti Condition="$(PackageJsonDevdependenciesJiti) == ''">^2.5.1</PackageJsonDevdependenciesJiti>
    <PackageJsonDevdependenciesPostcss Condition="$(PackageJsonDevdependenciesPostcss) == ''">^8.5.6</PackageJsonDevdependenciesPostcss>
    <PackageJsonDevdependenciesPostcssLoader Condition="$(PackageJsonDevdependenciesPostcssLoader) == ''">^8.2.0</PackageJsonDevdependenciesPostcssLoader>
    <PackageJsonDevdependenciesPrettier Condition="$(PackageJsonDevdependenciesPrettier) == ''">^3.6.2</PackageJsonDevdependenciesPrettier>
    <PackageJsonDevdependenciesStorybook Condition="$(PackageJsonDevdependenciesStorybook) == ''">^10.0.5</PackageJsonDevdependenciesStorybook>
    <PackageJsonDevdependenciesStyleLoader Condition="$(PackageJsonDevdependenciesStyleLoader) == ''">^4.0.0</PackageJsonDevdependenciesStyleLoader>
    <PackageJsonDevdependenciesTypescript Condition="$(PackageJsonDevdependenciesTypescript) == ''">^5.9.2</PackageJsonDevdependenciesTypescript>
    <PackageJsonDevdependenciesWebpack Condition="$(PackageJsonDevdependenciesWebpack) == ''">^5.101.3</PackageJsonDevdependenciesWebpack>
    <PackageJsonDevdependenciesWebpackCli Condition="$(PackageJsonDevdependenciesWebpackCli) == ''">^6.0.1</PackageJsonDevdependenciesWebpackCli>
    <PackageJsonDevdependenciesWebpackDevServer Condition="$(PackageJsonDevdependenciesWebpackDevServer) == ''">^5.2.2</PackageJsonDevdependenciesWebpackDevServer>
    <PackageJsonDependenciesAxios Condition="$(PackageJsonDependenciesAxios) == ''">^1.12.2</PackageJsonDependenciesAxios>
    <PackageJsonDependenciesBuffer Condition="$(PackageJsonDependenciesBuffer) == ''">^6.0.3</PackageJsonDependenciesBuffer>
    <PackageJsonDependenciesCopyWebpackPlugin Condition="$(PackageJsonDependenciesCopyWebpackPlugin) == ''">^13.0.1</PackageJsonDependenciesCopyWebpackPlugin>
    <PackageJsonDependenciesCrossEnv Condition="$(PackageJsonDependenciesCrossEnv) == ''">^10.0.0</PackageJsonDependenciesCrossEnv>
    <PackageJsonDependenciesCrypto Condition="$(PackageJsonDependenciesCrypto) == ''">^1.0.1</PackageJsonDependenciesCrypto>
    <PackageJsonDependenciesCryptoBrowserify Condition="$(PackageJsonDependenciesCryptoBrowserify) == ''">^3.12.1</PackageJsonDependenciesCryptoBrowserify>
    <PackageJsonDependenciesCryptoJs Condition="$(PackageJsonDependenciesCryptoJs) == ''">^4.2.0</PackageJsonDependenciesCryptoJs>
    <PackageJsonDependenciesDotenv Condition="$(PackageJsonDependenciesDotenv) == ''">^17.2.2</PackageJsonDependenciesDotenv>
    <PackageJsonDependenciesEslintPluginReact Condition="$(PackageJsonDependenciesEslintPluginReact) == ''">^7.37.5</PackageJsonDependenciesEslintPluginReact>
    <PackageJsonDependenciesEslintPluginReactHooks Condition="$(PackageJsonDependenciesEslintPluginReactHooks) == ''">^5.2.0</PackageJsonDependenciesEslintPluginReactHooks>
    <PackageJsonDependenciesJestEnvironmentJsdom Condition="$(PackageJsonDependenciesJestEnvironmentJsdom) == ''">^30.1.2</PackageJsonDependenciesJestEnvironmentJsdom>
    <PackageJsonDependenciesJsSha256 Condition="$(PackageJsonDependenciesJsSha256) == ''">^0.11.1</PackageJsonDependenciesJsSha256>
    <PackageJsonDependenciesJwtDecode Condition="$(PackageJsonDependenciesJwtDecode) == ''">^4.0.0</PackageJsonDependenciesJwtDecode>
    <PackageJsonDependenciesMarked Condition="$(PackageJsonDependenciesMarked) == ''">^17.0.0</PackageJsonDependenciesMarked>
    <PackageJsonDependenciesNpmCheckUpdates Condition="$(PackageJsonDependenciesNpmCheckUpdates) == ''">^18.1.1</PackageJsonDependenciesNpmCheckUpdates>
    <PackageJsonDependenciesReact Condition="$(PackageJsonDependenciesReact) == ''">^19.1.1</PackageJsonDependenciesReact>
    <PackageJsonDependenciesReactDom Condition="$(PackageJsonDependenciesReactDom) == ''">^19.1.1</PackageJsonDependenciesReactDom>
    <PackageJsonDependenciesReactHelmet Condition="$(PackageJsonDependenciesReactHelmet) == ''">^6.1.0</PackageJsonDependenciesReactHelmet>
    <PackageJsonDependenciesReactIcons Condition="$(PackageJsonDependenciesReactIcons) == ''">^5.5.0</PackageJsonDependenciesReactIcons>
    <PackageJsonDependenciesReactRouterDom Condition="$(PackageJsonDependenciesReactRouterDom) == ''">^7.9.1</PackageJsonDependenciesReactRouterDom>
    <PackageJsonDependenciesServe Condition="$(PackageJsonDependenciesServe) == ''">^14.2.5</PackageJsonDependenciesServe>
    <PackageJsonDependenciesSwaggerTypescriptApi Condition="$(PackageJsonDependenciesSwaggerTypescriptApi) == ''">^13.2.13</PackageJsonDependenciesSwaggerTypescriptApi>
  </PropertyGroup>
</Project>