{{- range .Values.redis.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  type: {{- if .nodePort }} NodePort {{- else }} ClusterIP {{- end }}
  ports:
    - port: 6379
      targetPort: 6379
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
  selector:
    app: {{ .name }}
{{- end }}
