{{- range .Values.mongodb }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.storage.mongodbData | default "5Gi" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.storage.mongodbConfig | default "1Gi" }}
---
{{- end }}
