{{- range .Values.sqlserver }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.storage.sqlserver | default "10Gi" }}
---
{{- end }}
