{{- range .Values.sqlserver.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: {{ .image }}:{{ $.Values.global.imageTag }}
          ports:
            - containerPort: 1433
          volumeMounts:
            - name: {{ .name }}-pvc
              mountPath: /var/opt/mssql
      volumes:
        - name: {{ .name }}-pvc
          persistentVolumeClaim:
            claimName: {{ .name }}-pvc
{{- end }}
