apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi
  labels:
    app: strapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      containers:
        - name: strapi
          image: strapi/strapi:latest
          ports:
            - containerPort: 1337
          volumeMounts:
            - name: strapi-pvc
              mountPath: /srv/app
      volumes:
        - name: strapi-pvc
          persistentVolumeClaim:
            claimName: strapi-pvc
      imagePullSecrets:
        - name: regcred
