export default {
  documentation: {
    enabled: true,
    config: {
      openapi: "3.0.0",
      info: {
        version: "1.0.0",
        title: "DJ Beat Blaster CMS API",
        description:
          "API documentation for DJ Beat Blaster CMS with JSON schemas",
        contact: {
          name: "DJ Beat Blaster Team",
          email: "support@djbeatblaster.com",
        },
      },
      servers: [
        {
          url: "http://localhost:1337/api",
          description: "Development server",
        },
        {
          url: "https://cms.djbeatblaster.com/api",
          description: "Production server",
        },
      ],
      // Enable automatic schema generation
      serveDocumentation: true,
      // Set the documentation path
      path: "/documentation",
      // Enable JSON schema export
      generateApi: true,
      // Auto-generate documentation from content types
      autoGenerateDocumentation: true,
    },
  },
  // Enable GraphQL plugin for additional API options
  graphql: {
    enabled: true,
    config: {
      endpoint: "/graphql",
      shadowCRUD: true,
      playgroundAlways: false,
      depthLimit: 7,
      amountLimit: 100,
      apolloServer: {
        tracing: false,
      },
    },
  },
};
