{{- range .Values.mongodb.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          iimage: {{ .image }}:{{ $.Values.global.imageTag }}
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: {{ .name }}-pvc
              mountPath: /data/db
            - name: {{ .name }}-config-pvc
              mountPath: /data/configdb
      volumes:
        - name: {{ .name }}-pvc
          persistentVolumeClaim:
            claimName: {{ .name }}-pvc
        - name: {{ .name }}-config-pvc
          persistentVolumeClaim:
            claimName: {{ .name }}-config-pvc
{{- end }}
