
# Use official .NET SDK as build stage
FROM mcr.microsoft.com/dotnet/sdk:9.0-alpine AS build

ARG MICROSERVICE_NAME

# Add all build-time args
ARG DATABASE_HOST_SQLSERVER
ARG DATABASE_PORT_SQLSERVER
ARG DATABASE_USER_SQLSERVER
ARG DATABASE_PASSWORD_SQLSERVER
ARG DATABASE_HOST_MONGODB
ARG DATABASE_PORT_MONGODB
ARG DATABASE_USER_MONGODB
ARG DATABASE_PASSWORD_MONGODB
ARG REDIS_HOST
ARG REDIS_PORT
ARG REDIS_PASSWORD
ARG RABBITMQ_HOST
ARG RABBITMQ_PORT
ARG RABBITMQ_USER
ARG RABBITMQ_PASSWORD
ARG SECURE_KEY
ARG JWT_KEY
ARG ENVIRONMENT
ARG IDENTITY_BE_ADDRESS
ARG MUSIC_BE_ADDRESS
ARG GEAR_BE_ADDRESS
ARG DOCUMENTS_BE_ADDRESS
ARG BRAND_BE_ADDRESS
ARG PARTY_BE_ADDRESS
ARG MAILING_BE_ADDRESS
ARG DATABASE_CATALOG
ARG DJPANEL_USER_EMAIL
ARG DJPANEL_USER_PASSWORD

# Set as ENV for runtime
ENV ASPNETCORE_DATABASE_HOST_SQLSERVER=$DATABASE_HOST_SQLSERVER
ENV ASPNETCORE_DATABASE_PORT_SQLSERVER=$DATABASE_PORT_SQLSERVER
ENV ASPNETCORE_DATABASE_USER_SQLSERVER=$DATABASE_USER_SQLSERVER
ENV ASPNETCORE_DATABASE_PASSWORD_SQLSERVER=$DATABASE_PASSWORD_SQLSERVER
ENV ASPNETCORE_DATABASE_HOST_MONGODB=$DATABASE_HOST_MONGODB
ENV ASPNETCORE_DATABASE_PORT_MONGODB=$DATABASE_PORT_MONGODB
ENV ASPNETCORE_DATABASE_USER_MONGODB=$DATABASE_USER_MONGODB
ENV ASPNETCORE_DATABASE_PASSWORD_MONGODB=$DATABASE_PASSWORD_MONGODB
ENV ASPNETCORE_REDIS_HOST=$REDIS_HOST
ENV ASPNETCORE_REDIS_PORT=$REDIS_PORT
ENV ASPNETCORE_REDIS_PASSWORD=$REDIS_PASSWORD
ENV ASPNETCORE_RABBITMQ_HOST=$RABBITMQ_HOST
ENV ASPNETCORE_RABBITMQ_PORT=$RABBITMQ_PORT
ENV ASPNETCORE_RABBITMQ_USER=$RABBITMQ_USER
ENV ASPNETCORE_RABBITMQ_PASSWORD=$RABBITMQ_PASSWORD
ENV ASPNETCORE_SECURE_KEY=$SECURE_KEY
ENV ASPNETCORE_JWT_KEY=$JWT_KEY
ENV ASPNETCORE_ENVIRONMENT=$ENVIRONMENT
ENV ASPNETCORE_IDENTITY_BE_ADDRESS=$IDENTITY_BE_ADDRESS
ENV ASPNETCORE_MUSIC_BE_ADDRESS=$MUSIC_BE_ADDRESS
ENV ASPNETCORE_GEAR_BE_ADDRESS=$GEAR_BE_ADDRESS
ENV ASPNETCORE_DOCUMENTS_BE_ADDRESS=$DOCUMENTS_BE_ADDRESS
ENV ASPNETCORE_BRAND_BE_ADDRESS=$BRAND_BE_ADDRESS
ENV ASPNETCORE_PARTY_BE_ADDRESS=$PARTY_BE_ADDRESS
ENV ASPNETCORE_MAILING_BE_ADDRESS=$MAILING_BE_ADDRESS
ENV ASPNETCORE_DATABASE_CATALOG=$DATABASE_CATALOG
ENV ASPNETCORE_DJPANEL_USER_EMAIL=$DJPANEL_USER_EMAIL
ENV ASPNETCORE_DJPANEL_USER_PASSWORD=$DJPANEL_USER_PASSWORD

RUN apt-get update


# Set WORKDIR before COPY (DL3045)
WORKDIR /src

# Copy only csproj and restore as distinct layers for better cache
COPY Services/${MICROSERVICE_NAME}/*.csproj ./Services/${MICROSERVICE_NAME}/
COPY Services/Shared/*.csproj ./Services/Shared/
RUN dotnet restore Services/${MICROSERVICE_NAME}/*.csproj --no-cache

# Copy the rest of the source code
COPY Services/${MICROSERVICE_NAME}/ ./Services/${MICROSERVICE_NAME}/
COPY Services/Shared/ ./Services/Shared/

# Build and publish
WORKDIR /src/Services/${MICROSERVICE_NAME}/
RUN dotnet publish -c Release -o /app/publish --no-restore --no-build --self-contained false /p:UseAppHost=false || dotnet build -c Release -o /app/build --no-restore && dotnet publish -c Release -o /app/publish --no-restore /p:UseAppHost=false



# Use minimal runtime image
FROM mcr.microsoft.com/dotnet/aspnet:9.0-alpine AS base
SHELL ["/bin/sh","-c"]

# Install curl for healthcheck (alpine)
# hadolint ignore=DL3018
RUN apk add --no-cache curl

EXPOSE 8080
ARG MICROSERVICE_NAME

# Add all build-time args
ARG DATABASE_HOST_SQLSERVER
ARG DATABASE_PORT_SQLSERVER
ARG DATABASE_USER_SQLSERVER
ARG DATABASE_PASSWORD_SQLSERVER
ARG DATABASE_HOST_MONGODB
ARG DATABASE_PORT_MONGODB
ARG DATABASE_USER_MONGODB
ARG DATABASE_PASSWORD_MONGODB
ARG REDIS_HOST
ARG REDIS_PORT
ARG REDIS_PASSWORD
ARG RABBITMQ_HOST
ARG RABBITMQ_PORT
ARG RABBITMQ_USER
ARG RABBITMQ_PASSWORD
ARG SECURE_KEY
ARG JWT_KEY
ARG ENVIRONMENT
ARG IDENTITY_BE_ADDRESS
ARG MUSIC_BE_ADDRESS
ARG GEAR_BE_ADDRESS
ARG DOCUMENTS_BE_ADDRESS
ARG BRAND_BE_ADDRESS
ARG PARTY_BE_ADDRESS
ARG MAILING_BE_ADDRESS
ARG DATABASE_CATALOG
ARG DJPANEL_USER_EMAIL
ARG DJPANEL_USER_PASSWORD

# Set as ENV for runtime
ENV ASPNETCORE_DATABASE_HOST_SQLSERVER=$DATABASE_HOST_SQLSERVER
ENV ASPNETCORE_DATABASE_PORT_SQLSERVER=$DATABASE_PORT_SQLSERVER
ENV ASPNETCORE_DATABASE_USER_SQLSERVER=$DATABASE_USER_SQLSERVER
ENV ASPNETCORE_DATABASE_PASSWORD_SQLSERVER=$DATABASE_PASSWORD_SQLSERVER
ENV ASPNETCORE_DATABASE_HOST_MONGODB=$DATABASE_HOST_MONGODB
ENV ASPNETCORE_DATABASE_PORT_MONGODB=$DATABASE_PORT_MONGODB
ENV ASPNETCORE_DATABASE_USER_MONGODB=$DATABASE_USER_MONGODB
ENV ASPNETCORE_DATABASE_PASSWORD_MONGODB=$DATABASE_PASSWORD_MONGODB
ENV ASPNETCORE_REDIS_HOST=$REDIS_HOST
ENV ASPNETCORE_REDIS_PORT=$REDIS_PORT
ENV ASPNETCORE_REDIS_PASSWORD=$REDIS_PASSWORD
ENV ASPNETCORE_RABBITMQ_HOST=$RABBITMQ_HOST
ENV ASPNETCORE_RABBITMQ_PORT=$RABBITMQ_PORT
ENV ASPNETCORE_RABBITMQ_USER=$RABBITMQ_USER
ENV ASPNETCORE_RABBITMQ_PASSWORD=$RABBITMQ_PASSWORD
ENV ASPNETCORE_SECURE_KEY=$SECURE_KEY
ENV ASPNETCORE_JWT_KEY=$JWT_KEY
ENV ASPNETCORE_ENVIRONMENT=$ENVIRONMENT
ENV ASPNETCORE_IDENTITY_BE_ADDRESS=$IDENTITY_BE_ADDRESS
ENV ASPNETCORE_MUSIC_BE_ADDRESS=$MUSIC_BE_ADDRESS
ENV ASPNETCORE_GEAR_BE_ADDRESS=$GEAR_BE_ADDRESS
ENV ASPNETCORE_DOCUMENTS_BE_ADDRESS=$DOCUMENTS_BE_ADDRESS
ENV ASPNETCORE_BRAND_BE_ADDRESS=$BRAND_BE_ADDRESS
ENV ASPNETCORE_PARTY_BE_ADDRESS=$PARTY_BE_ADDRESS
ENV ASPNETCORE_MAILING_BE_ADDRESS=$MAILING_BE_ADDRESS
ENV ASPNETCORE_DATABASE_CATALOG=$DATABASE_CATALOG
ENV ASPNETCORE_DJPANEL_USER_EMAIL=$DJPANEL_USER_EMAIL
ENV ASPNETCORE_DJPANEL_USER_PASSWORD=$DJPANEL_USER_PASSWORD


WORKDIR /app
COPY --from=build /app/publish/ .

ENV APP_EXE=${MICROSERVICE_NAME}.dll

# Use JSON notation with shell -c for env var substitution
ENTRYPOINT ["sh", "-c", "dotnet $APP_EXE"]

HEALTHCHECK --interval=10s --timeout=5s --start-period=180s --retries=6 \
  CMD curl -fsS http://localhost:8080/healthz/live \
   || curl -fsS http://localhost:8080/health \
   || curl -fsS http://localhost:8080/ \
   || exit 1
