# --- Build Stage ---
FROM mcr.microsoft.com/dotnet/sdk:9.0-alpine AS build
ARG MICROSERVICE_NAME
WORKDIR /src
COPY Services/${MICROSERVICE_NAME}/*.csproj ./Services/${MICROSERVICE_NAME}/
COPY Services/Shared/*.csproj ./Services/Shared/
RUN dotnet restore Services/${MICROSERVICE_NAME}/*.csproj --no-cache
COPY Services/${MICROSERVICE_NAME}/ ./Services/${MICROSERVICE_NAME}/
COPY Services/Shared/ ./Services/Shared/
WORKDIR /src/Services/${MICROSERVICE_NAME}/
RUN dotnet publish -c Release -o /app/publish --no-restore /p:UseAppHost=false

# --- Runtime Stage ---
FROM mcr.microsoft.com/dotnet/aspnet:9.0-alpine AS runtime
ARG MICROSERVICE_NAME
ARG DATABASE_HOST_SQLSERVER
ARG DATABASE_PORT_SQLSERVER
ARG DATABASE_USER_SQLSERVER
ARG DATABASE_PASSWORD_SQLSERVER
ARG DATABASE_HOST_MONGODB
ARG DATABASE_PORT_MONGODB
ARG DATABASE_USER_MONGODB
ARG DATABASE_PASSWORD_MONGODB
ARG REDIS_HOST
ARG REDIS_PORT
ARG REDIS_PASSWORD
ARG RABBITMQ_HOST
ARG RABBITMQ_PORT
ARG RABBITMQ_USER
ARG RABBITMQ_PASSWORD
ARG SECURE_KEY
ARG JWT_KEY
ARG ENVIRONMENT
ARG IDENTITY_BE_ADDRESS
ARG MUSIC_BE_ADDRESS
ARG GEAR_BE_ADDRESS
ARG DOCUMENTS_BE_ADDRESS
ARG BRAND_BE_ADDRESS
ARG PARTY_BE_ADDRESS
ARG MAILING_BE_ADDRESS
ARG DATABASE_CATALOG
ARG DJPANEL_USER_EMAIL
ARG DJPANEL_USER_PASSWORD
WORKDIR /app
COPY --from=build /app/publish/ .
ENV APP_EXE=${MICROSERVICE_NAME}.dll \
	ASPNETCORE_DATABASE_HOST_SQLSERVER=$DATABASE_HOST_SQLSERVER \
	ASPNETCORE_DATABASE_PORT_SQLSERVER=$DATABASE_PORT_SQLSERVER \
	ASPNETCORE_DATABASE_USER_SQLSERVER=$DATABASE_USER_SQLSERVER \
	ASPNETCORE_DATABASE_PASSWORD_SQLSERVER=$DATABASE_PASSWORD_SQLSERVER \
	ASPNETCORE_DATABASE_HOST_MONGODB=$DATABASE_HOST_MONGODB \
	ASPNETCORE_DATABASE_PORT_MONGODB=$DATABASE_PORT_MONGODB \
	ASPNETCORE_DATABASE_USER_MONGODB=$DATABASE_USER_MONGODB \
	ASPNETCORE_DATABASE_PASSWORD_MONGODB=$DATABASE_PASSWORD_MONGODB \
	ASPNETCORE_REDIS_HOST=$REDIS_HOST \
	ASPNETCORE_REDIS_PORT=$REDIS_PORT \
	ASPNETCORE_REDIS_PASSWORD=$REDIS_PASSWORD \
	ASPNETCORE_RABBITMQ_HOST=$RABBITMQ_HOST \
	ASPNETCORE_RABBITMQ_PORT=$RABBITMQ_PORT \
	ASPNETCORE_RABBITMQ_USER=$RABBITMQ_USER \
	ASPNETCORE_RABBITMQ_PASSWORD=$RABBITMQ_PASSWORD \
	ASPNETCORE_SECURE_KEY=$SECURE_KEY \
	ASPNETCORE_JWT_KEY=$JWT_KEY \
	ASPNETCORE_ENVIRONMENT=$ENVIRONMENT \
	ASPNETCORE_IDENTITY_BE_ADDRESS=$IDENTITY_BE_ADDRESS \
	ASPNETCORE_MUSIC_BE_ADDRESS=$MUSIC_BE_ADDRESS \
	ASPNETCORE_GEAR_BE_ADDRESS=$GEAR_BE_ADDRESS \
	ASPNETCORE_DOCUMENTS_BE_ADDRESS=$DOCUMENTS_BE_ADDRESS \
	ASPNETCORE_BRAND_BE_ADDRESS=$BRAND_BE_ADDRESS \
	ASPNETCORE_PARTY_BE_ADDRESS=$PARTY_BE_ADDRESS \
	ASPNETCORE_MAILING_BE_ADDRESS=$MAILING_BE_ADDRESS \
	ASPNETCORE_DATABASE_CATALOG=$DATABASE_CATALOG \
	ASPNETCORE_DJPANEL_USER_EMAIL=$DJPANEL_USER_EMAIL \
	ASPNETCORE_DJPANEL_USER_PASSWORD=$DJPANEL_USER_PASSWORD
ENTRYPOINT ["sh", "-c", "dotnet $APP_EXE"]
EXPOSE 8080

HEALTHCHECK --interval=10s --timeout=5s --start-period=180s --retries=6 \
  CMD curl -fsS http://localhost:8080/healthz/live \
   || curl -fsS http://localhost:8080/health \
   || curl -fsS http://localhost:8080/ \
   || exit 1
