name: Release Projects

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - DEV
          - PREPROD
          - PROD
jobs:
  release_artifacts:
    name: Release Artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [
          'Services/CompanyAPI',
          'Services/DJHostGateway',
          'Services/DocumentsAPI',
          'Services/EquipmentAPI',
          'Services/IdentityAPI',
          'Services/MailingAPI',
          'Services/MusicAPI',
          'Services/PartyAPI',
          'Frontends/DJPanel',
          'Frontends/Identity',
          'Frontends/Music'
        ]
    steps:
    - name: Prepare artifact name
      id: prepare-name
      run: echo "artifact_name=$(echo ${{ matrix.service }} | tr '/' '.')" >> $GITHUB_OUTPUT
    - name: Get Latest Date Signed Artifact
      id: get-latest-artifact
      run: |
        # Assuming artifacts are stored in a predictable location (e.g., releases directory)
        latest_artifact=$(ls -1tr ${{ github.event.inputs.environment }}.${{ steps.prepare-name.outputs.artifact_name }}*.zip | tail -1)
        echo "latest_artifact=$latest_artifact" >> $GITHUB_OUTPUT
    - name: Check if artifact was already released
      id: check-release
      run: |
        artifact_name=$(basename ${{ steps.get-latest-artifact.outputs.latest_artifact }})
        if gh release list | grep -q "$artifact_name"; then
          echo "already_released=true" >> $GITHUB_OUTPUT
        else
          echo "already_released=false" >> $GITHUB_OUTPUT
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/download-artifact@v3
      if: steps.check-release.outputs.already_released == 'false'
      with:
        name: ${{ steps.get-latest-artifact.outputs.latest_artifact }}
        path: build
    - name: Create release package
      if: steps.check-release.outputs.already_released == 'false'
      run: zip -r build.zip build/
    - uses: ncipollo/release-action@v1
      if: steps.check-release.outputs.already_released == 'false'
      with:
        artifacts: "build.zip"
        allowUpdates: 'true'
