name: release Projects

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - DEV
          - PREPROD
          - PROD
jobs:
  release_dotnet:
    name: Release - DotNet
    runs-on: ubuntu-latest
    steps:
      - name: Check artifacts
        uses: actions/checkout@v4
