name: Update TrueNAS Infrastructure

on:
  workflow_dispatch:

jobs:
  update_infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Infrastructure Code
        uses: actions/checkout@v5

      - name: Update TrueNAS Infrastructure (SSH)
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            echo "Running on host: $(hostname)"
