name: Build Projects

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - Development
          - Preproduction
          - Production
        default: 'Development'

jobs:
  set_date:
    name: Set Date
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    outputs:
      date: ${{ steps.set-date.outputs.date }}
    steps:
      - name: Set Date
        id: set-date
        run: echo "date=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
  validate_dotnet:
    needs: set_date
    name: Build - DotNet
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    strategy:
      matrix:
        service: [
          'Services/CompanyAPI',
          'Services/DJHostGateway',
          'Services/DocumentsAPI',
          'Services/EquipmentAPI',
          'Services/IdentityAPI',
          'Services/MailingAPI',
          'Services/MusicAPI',
          'Services/PartyAPI'
        ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2  # Potrzebujemy poprzedniego commita do porównania
    - name: Check if service changed
      id: check_changes
      uses: dorny/paths-filter@v3
      with:
        filters: |
          service:
            - '${{ matrix.service }}/**'
    - name: Setup .NET
      if: steps.check_changes.outputs.service == 'true'
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.x'
    - name: Restore dependencies
      if: steps.check_changes_dotnet.outputs.service == 'true'
      run: dotnet restore ${{ matrix.service }}
    - name: Build
      if: steps.check_changes_dotnet.outputs.service == 'true'
      run: dotnet build ${{ matrix.service }} --no-restore --configuration Release
    - name: Prepare artifact name
      if: steps.check_changes_dotnet.outputs.service == 'true'
      id: prepare-name
      run: echo "artifact_name=$(echo ${{ matrix.service }} | tr '/' '.')" >> $GITHUB_OUTPUT
    - name: Create artifact
      if: steps.check_changes_dotnet.outputs.service == 'true'
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.event.inputs.environment }}.${{ steps.prepare-name.outputs.artifact_name }}.${{ needs.set_date.outputs.date }}
        path: ${{ matrix.service }}/bin/Release/net9.0/
  build_react:
    needs: set_date
    name: Build - React
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    strategy:
      matrix:
        service: [
          'Frontends/DJPanel',
          'Frontends/Identity',
          'Frontends/Music'
        ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2  # Potrzebujemy poprzedniego commita do porównania
    - name: Check if frontend changed
      id: check_changes
      uses: dorny/paths-filter@v3
      with:
        filters: |
          frontend:
            - '${{ matrix.service }}/**'
    - name: Use Node version
      if: steps.check_changes.outputs.service == 'true'
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: Install dependencies
      if: steps.check_changes_react.outputs.service == 'true'
      run: npm install
      working-directory: ${{ matrix.service }}
    - name: Build
      if: steps.check_changes_react.outputs.service == 'true'
      run: npm run build
      working-directory: ${{ matrix.service }}
    - name: Prepare artifact name
      if: steps.check_changes_react.outputs.service == 'true'
      id: prepare-name
      run: echo "artifact_name=$(echo ${{ matrix.service }} | tr '/' '.')" >> $GITHUB_OUTPUT
    - name: Create artifact
      if: steps.check_changes_react.outputs.service == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.inputs.environment }}.${{ steps.prepare-name.outputs.artifact_name }}.${{ needs.set_date.outputs.date }}
        path: ${{ matrix.service }}/dist/

    


