name: Build Artifacts

on:
  push:
    branches:
      - "releases/R*"
  workflow_dispatch:

jobs:
  determine_environment:
    name: Determine Environment
    runs-on: ubuntu-latest
    outputs:
      current_env: ${{ steps.set_env.outputs.current_env }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v5
      - name: Set Environment
        id: set_env
        uses: ./.github/templates/determine-environment

  determine_target_branch:
    name: Determine Target Branch
    runs-on: ubuntu-latest
    outputs:
      target_branch: ${{ steps.branch_set.outputs.target_branch }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v5
      - name: Determine target branch based on branch
        id: branch_set
        uses: ./.github/templates/determine-target-branch

  determine_docker_tag:
    name: Determine Docker Tag
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{ steps.tag_set.outputs.docker_tag }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v5
      - name: Determine Docker tag based on branch
        id: tag_set
        uses: ./.github/templates/determine-docker-tag

  build_dotnet_services:
    environment: ${{ needs.determine_environment.outputs.current_env }}
    name: Build & Push .NET Services
    needs:
      - determine_environment
      - determine_target_branch
      - determine_docker_tag
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        service:
          [
            "CompanyAPI",
            "DJHostGateway",
            "DocumentsAPI",
            "EquipmentAPI",
            "IdentityAPI",
            "MailingAPI",
            "MusicAPI",
            "PartyAPI",
          ]
    env:
      DATABASE_HOST_SQLSERVER: ${{ vars.DATABASE_HOST_SQLSERVER }}
      DATABASE_PORT_SQLSERVER: ${{ vars.DATABASE_PORT_SQLSERVER }}
      DATABASE_USER_SQLSERVER: ${{ vars.DATABASE_USER_SQLSERVER }}
      DATABASE_PASSWORD_SQLSERVER: ${{ secrets.DATABASE_PASSWORD_SQLSERVER }}
      DATABASE_HOST_MONGODB: ${{ vars.DATABASE_HOST_MONGODB }}
      DATABASE_PORT_MONGODB: ${{ vars.DATABASE_PORT_MONGODB }}
      DATABASE_USER_MONGODB: ${{ vars.DATABASE_USER_MONGODB }}
      DATABASE_PASSWORD_MONGODB: ${{ secrets.DATABASE_PASSWORD_MONGODB }}
      REDIS_HOST: ${{ vars.REDIS_HOST }}
      REDIS_PORT: ${{ vars.REDIS_PORT }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      RABBITMQ_HOST: ${{ vars.RABBITMQ_HOST }}
      RABBITMQ_PORT: ${{ vars.RABBITMQ_PORT }}
      RABBITMQ_USER: ${{ vars.RABBITMQ_USER }}
      RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
      SECURE_KEY: ${{ secrets.SECURE_KEY }}
      JWT_KEY: ${{ secrets.JWT_KEY }}
      ASPNETCORE_ENVIRONMENT: ${{ vars.ASPNETCORE_ENVIRONMENT }}
      ASPNETCORE_IDENTITY_BE_ADDRESS: ${{ vars.ASPNETCORE_IDENTITY_BE_ADDRESS }}
      ASPNETCORE_MUSIC_BE_ADDRESS: ${{ vars.ASPNETCORE_MUSIC_BE_ADDRESS }}
      ASPNETCORE_GEAR_BE_ADDRESS: ${{ vars.ASPNETCORE_GEAR_BE_ADDRESS }}
      ASPNETCORE_DOCUMENTS_BE_ADDRESS: ${{ vars.ASPNETCORE_DOCUMENTS_BE_ADDRESS }}
      ASPNETCORE_BRAND_BE_ADDRESS: ${{ vars.ASPNETCORE_BRAND_BE_ADDRESS }}
      ASPNETCORE_PARTY_BE_ADDRESS: ${{ vars.ASPNETCORE_PARTY_BE_ADDRESS }}
      ASPNETCORE_MAILING_BE_ADDRESS: ${{ vars.ASPNETCORE_MAILING_BE_ADDRESS }}
      DATABASE_CATALOG: ${{ matrix.service }}
      DJPANEL_USER_EMAIL: ${{ vars.DJPANEL_USER_EMAIL }}
      DJPANEL_USER_PASSWORD: ${{ secrets.DJPANEL_USER_PASSWORD }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v5

      - name: Build .NET Service
        uses: ./.github/templates/build-dotnet-service
        with:
          service: ${{ matrix.service }}

      - name: Login and Push to GitHub Container Registry
        uses: ./.github/templates/ghcr
        with:
          tag: ghcr.io/${{ github.repository_owner }}/micros/services/${{ matrix.service }}:${{ needs.determine_docker_tag.outputs.docker_tag }}-latest
          dockerfile: Docker/microservice.Dockerfile
          github-token: ${{ secrets.GITHUB_TOKEN }}
          build-args: |
            MICROSERVICE_NAME=${{ matrix.service }}
            DATABASE_HOST_SQLSERVER=${{ env.DATABASE_HOST_SQLSERVER }}
            DATABASE_PORT_SQLSERVER=${{ env.DATABASE_PORT_SQLSERVER }}
            DATABASE_USER_SQLSERVER=${{ env.DATABASE_USER_SQLSERVER }}
            DATABASE_PASSWORD_SQLSERVER=${{ env.DATABASE_PASSWORD_SQLSERVER }}
            DATABASE_HOST_MONGODB=${{ env.DATABASE_HOST_MONGODB }}
            DATABASE_PORT_MONGODB=${{ env.DATABASE_PORT_MONGODB }}
            DATABASE_USER_MONGODB=${{ env.DATABASE_USER_MONGODB }}
            DATABASE_PASSWORD_MONGODB=${{ env.DATABASE_PASSWORD_MONGODB }}
            REDIS_HOST=${{ env.REDIS_HOST }}
            REDIS_PORT=${{ env.REDIS_PORT }}
            REDIS_PASSWORD=${{ env.REDIS_PASSWORD }}
            RABBITMQ_HOST=${{ env.RABBITMQ_HOST }}
            RABBITMQ_PORT=${{ env.RABBITMQ_PORT }}
            RABBITMQ_USER=${{ env.RABBITMQ_USER }}
            RABBITMQ_PASSWORD=${{ env.RABBITMQ_PASSWORD }}
            SECURE_KEY=${{ env.SECURE_KEY }}
            JWT_KEY=${{ env.JWT_KEY }}
            ASPNETCORE_ENVIRONMENT=${{ env.ASPNETCORE_ENVIRONMENT }}
            ASPNETCORE_IDENTITY_BE_ADDRESS=${{ env.ASPNETCORE_IDENTITY_BE_ADDRESS }}
            ASPNETCORE_MUSIC_BE_ADDRESS=${{ env.ASPNETCORE_MUSIC_BE_ADDRESS }}
            ASPNETCORE_GEAR_BE_ADDRESS=${{ env.ASPNETCORE_GEAR_BE_ADDRESS }}
            ASPNETCORE_DOCUMENTS_BE_ADDRESS=${{ env.ASPNETCORE_DOCUMENTS_BE_ADDRESS }}
            ASPNETCORE_BRAND_BE_ADDRESS=${{ env.ASPNETCORE_BRAND_BE_ADDRESS }}
            ASPNETCORE_PARTY_BE_ADDRESS=${{ env.ASPNETCORE_PARTY_BE_ADDRESS }}
            ASPNETCORE_MAILING_BE_ADDRESS=${{ env.ASPNETCORE_MAILING_BE_ADDRESS }}
            DATABASE_CATALOG=${{ env.DATABASE_CATALOG }}
            DJPANEL_USER_EMAIL=${{ env.DJPANEL_USER_EMAIL }}
            DJPANEL_USER_PASSWORD=${{ env.DJPANEL_USER_PASSWORD }}

  build_react_frontends:
    environment: ${{ needs.determine_environment.outputs.current_env }}
    name: Build & Push React Frontends
    needs:
      - determine_environment
      - determine_target_branch
      - determine_docker_tag
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        service: ["dj-panel"]
    env:
      REACT_APP_API_GATEWAY: ${{ vars.REACT_APP_API_GATEWAY }}
      REACT_APP_API_SECURE_KEY: ${{ secrets.SECURE_KEY }}
      REACT_APP_API_JWT_TOKEN: ${{ secrets.JWT_KEY }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v5

      - name: Build React Service
        uses: ./.github/templates/build-react-service
        with:
          service: ${{ matrix.service }}

      - name: Login and Push to GitHub Container Registry
        uses: ./.github/templates/ghcr
        with:
          tag: ghcr.io/${{ github.repository_owner }}/micros/frontends/${{ matrix.service }}:${{ needs.determine_docker_tag.outputs.docker_tag }}-latest
          dockerfile: Docker/microfrontend.Dockerfile
          github-token: ${{ secrets.GITHUB_TOKEN }}
          build-args: |
            MICROFRONTEND_NAME=${{ matrix.service }}
            REACT_APP_API_GATEWAY=${{ env.REACT_APP_API_GATEWAY }}
            REACT_APP_API_SECURE_KEY=${{ env.REACT_APP_API_SECURE_KEY }}
            REACT_APP_API_JWT_TOKEN=${{ env.REACT_APP_API_JWT_TOKEN }}

  build_infrastructure_images:
    name: Build & Push Infrastructure Images
    needs:
      - determine_target_branch
      - determine_docker_tag
      - determine_environment
    runs-on: ubuntu-latest
    environment: ${{ needs.determine_environment.outputs.current_env }}
    timeout-minutes: 15
    strategy:
      matrix:
        image:
          - {
              name: "mongodb",
              dockerfile: "Docker/mongodb.Dockerfile",
              tag: "mongodb",
            }
          - {
              name: "postgres",
              dockerfile: "Docker/postgres.Dockerfile",
              tag: "postgres",
            }
          - {
              name: "redis",
              dockerfile: "Docker/redis.Dockerfile",
              tag: "redis",
            }
          - {
              name: "rabbitmq",
              dockerfile: "Docker/rabbitmq.Dockerfile",
              tag: "rabbitmq",
            }
          - {
              name: "sqlserver",
              dockerfile: "Docker/sqlserver.Dockerfile",
              tag: "sqlserver",
            }
          - {
              name: "strapi",
              dockerfile: "Docker/strapi.Dockerfile",
              tag: "strapi",
            }
    env:
      DATABASE_USER_MONGODB: ${{ vars.DATABASE_USER_MONGODB }}
      DATABASE_PASSWORD_MONGODB: ${{ secrets.DATABASE_PASSWORD_MONGODB }}
      CMS_DATABASE_NAME: ${{ vars.CMS_DATABASE_NAME }}
      CMS_DATABASE_USERNAME: ${{ vars.CMS_DATABASE_USERNAME }}
      CMS_DATABASE_PASSWORD: ${{ secrets.CMS_DATABASE_PASSWORD }}
      CMS_DATABASE_CLIENT: ${{ vars.CMS_DATABASE_CLIENT }}
      CMS_NODE_ENV: ${{ vars.CMS_NODE_ENV }}
      CMS_DATABASE_HOST: ${{ vars.CMS_DATABASE_HOST }}
      CMS_DATABASE_PORT: ${{ vars.CMS_DATABASE_PORT }}
      CMS_JWT_SECRET: ${{ secrets.CMS_JWT_SECRET }}
      CMS_ADMIN_JWT_SECRET: ${{ secrets.CMS_ADMIN_JWT_SECRET }}
      CMS_APP_KEYS: ${{ secrets.CMS_APP_KEYS }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      RABBITMQ_USER: ${{ vars.RABBITMQ_USER }}
      RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
      DATABASE_PASSWORD_SQLSERVER: ${{ secrets.DATABASE_PASSWORD_SQLSERVER }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v5

      - name: Login and Push to GitHub Container Registry
        uses: ./.github/templates/ghcr
        with:
          tag: ghcr.io/${{ github.repository_owner }}/micros/infra/${{ matrix.image.name }}:${{ needs.determine_docker_tag.outputs.docker_tag }}-latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ${{ matrix.image.dockerfile }}
