name: Create Release Branch

on:
  pull_request:
    types:
      - closed
    branches:
      - production
  workflow_dispatch:

jobs:
  create-release-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Get current year and month
        id: date
        run: |
          YY=$(date +'%y')
          MM=$(date +'%m')
          echo "branch=releases/R${YY}${MM}" >> "$GITHUB_OUTPUT"

      - name: Delete merged branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branches: ${{ github.event.pull_request.head.ref }}

      - name: Create release branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: refs/heads/${{ steps.date.outputs.branch }}
          sha: ${{ github.event.pull_request.head.sha }}
