name: PR Validation

on:
  pull_request:
    branches: 
      - develop
      - 'release/**'
    types: [opened, synchronize, reopened]

jobs:
  validate:
    name: Validate PR
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore Services/DJHostGateway/DJHostGateway.sln
      
    - name: Build
      run: dotnet build Services/DJHostGateway/DJHostGateway.sln --no-restore --configuration Release