name: PR Validation

on:
  pull_request:
    branches: [develop, 'release/**']

jobs:
  changed_files:
    name: Detect changed directories
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.filter.outputs.services }}
      frontends: ${{ steps.filter.outputs.frontends }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            services:
              - 'Services/**'
            frontends:
              - 'Frontends/**'

  validate_dotnet:
    needs: changed_files
    if: ${{ needs.changed_files.outputs.services == 'true' }}
    name: Validate PR - DotNet
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [
          'Services/CompanyAPI',
          'Services/DJHostGateway',
          'Services/DocumentsAPI',
          'Services/EquipmentAPI',
          'Services/IdentityAPI',
          'Services/MailingAPI',
          'Services/MusicAPI',
          'Services/PartyAPI'
        ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Check if service changed
      id: check_changes
      uses: dorny/paths-filter@v2
      with:
        filters: |
          service:
            - '${{ matrix.service }}/**'
    - name: Setup .NET
      if: steps.check_changes.outputs.service == 'true'
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.x'
    - name: Restore dependencies
      if: steps.check_changes.outputs.service == 'true'
      run: dotnet restore ${{ matrix.service }}
    - name: Build
      if: steps.check_changes.outputs.service == 'true'
      run: dotnet build ${{ matrix.service }} --no-restore --configuration Release

  validate_react:
    needs: changed_files
    if: ${{ needs.changed_files.outputs.frontends == 'true' }}
    name: Validate PR - React
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [
          'Frontends/DJPanel',
          'Frontends/Identity',
          'Frontends/Music'
        ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Check if frontend changed
      id: check_changes
      uses: dorny/paths-filter@v2
      with:
        filters: |
          frontend:
            - '${{ matrix.service }}/**'
    - name: Use Node version
      if: steps.check_changes.outputs.frontend == 'true'
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: Install dependencies
      if: steps.check_changes.outputs.frontend == 'true'
      run: npm install
      working-directory: ${{ matrix.service }}
    - name: Build
      if: steps.check_changes.outputs.frontend == 'true'
      run: npm run build
      working-directory: ${{ matrix.service }}
    

    

